version: "3"

services:
  db:
    image: postgres:latest
    container_name: apiclient-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=client
      - POSTGRES_USER=postgres
    networks:
      - backend
  app:
    build: 
      dockerfile: Dockerfile
      context: ./packages/backend
    container_name: apiclient-api
    ports:
      - "3333:3333"
    volumes:
      - ./packages/backend:/app/build
    command: 
      yarn dev
      yarn typeorm migration:run 
    networks:
      - frontend
      - backend
    environment:
      FRONT_URL: http://localhost:5173

    depends_on:
      - db
  front:
    build: 
      dockerfile: Dockerfile
      context: ./packages/navbar
    links:
      - "app"
    container_name: frontclient-api
    ports:
      - "5173:5173"
    volumes:
      - ./packages/navbar:/front/build
    networks:
      - frontend
    environment:
      HOST_API: http://app:3333/
      TOKEN_API: guzela
    depends_on:
      - app
    
networks:
  frontend:
    
  backend:
    

volumes:
  pgdata:
    driver: local

