version: "3"

services:
  db:
    image: postgres:latest
    container_name: apiclient-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=client
      - POSTGRES_USER=postgres
    networks:
      - backend
  app:
    build:
      dockerfile: Dockerfile
      context: ./packages/backend
    container_name: apiclient-api
    ports:
      - "3333:3333"
    volumes:
      - ./packages/backend:/app/build
    networks:
      - frontend
      - backend

    depends_on:
      - db
  front:
    build:
      dockerfile: Dockerfile
      context: ./packages/navbar
    links:
      - "app"
    container_name: frontclient-api
    ports:
      - "5173:5173"
    volumes:
      - ./packages/navbar:/front/build
    networks:
      - frontend
    environment:
      - HOST_API=http://localhost/clients
      - TOKEN_API=guzela
    depends_on:
      - app
  cors:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: cors
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - app
      - db

networks:
  frontend:
  backend:


volumes:
  pgdata:
    driver: local
